### PR TITLE
Add Smokey test for Collections Publisher

### PR DESCRIPTION
**Pull request by ChrisBAshton**
We've now added a healthcheck endpoint (https://github.com/alphagov/collections-publisher/pull/1199) and ensured that Smokey can access it (https://github.com/alphagov/collections-publisher/pull/1203).

## Testing

**You should manually test your PR before merging.**

This app doesn't have CI setup, and it would be misleading to do so:
the behaviour of the tests changes depending on the environment they
are run in. You should manually test in applicable environments,
until you are confident your change is not a breaking one.

Example steps to test in Integration:

- Click "Configure" for the [Smokey job][]
- Change the "Branch specifier" to the name of your branch
- Run a new build of the Smokey project and check the results

## Deployment

**You need to manually deploy your PR after merging.**

Steps to deploy a change:

- Run the [Smokey deploy job][] to deploy the [continuous Smokey loop][]
- Repeat this in Staging and Production

> The manual [Smokey job][] will pick up changes on `master` automatically. You only need to do a manual deployment for the [continuous Smokey loop][].

[Smokey job]: https://deploy.integration.publishing.service.gov.uk/job/Smokey/
[continuous Smokey loop]: https://github.com/alphagov/govuk-puppet/blob/master/modules/monitoring/templates/smokey-loop.conf
[Smokey deploy job]: https://deploy.integration.publishing.service.gov.uk/job/Smokey_Deploy/

### CODE REVIEW

**Comment by ChrisBAshton** [comment]
This is now passing: https://deploy.integration.publishing.service.gov.uk/job/Smokey/25285/console

**Comment by thomasleese** [comment]
I think we'll need to add the tag to this as well: https://github.com/alphagov/smokey/blob/1f1ffe4d5ec16556e03dc73592d8be40da6515dc/features/publishing_tools.feature#L3-L10

**Review by Rosa-Fox — APPROVED** [review]
[Tested here](https://deploy.integration.publishing.service.gov.uk/job/Smokey/25287/)

**Comment by ChrisBAshton** [comment]
> I think we'll need to add the tag to this as well:
> 
> https://github.com/alphagov/smokey/blob/1f1ffe4d5ec16556e03dc73592d8be40da6515dc/features/publishing_tools.feature#L3-L10

Oops, good spot! Added.

**Review by thomasleese — APPROVED** [review]

**Pull request merged**
