### PR TITLE
Comment out info-frontend unique pageviews

### PR DESCRIPTION
**Pull request by richardTowers**
## Testing

**You should manually test your PR before merging.**

This app doesn't have CI setup, and it would be misleading to do so:
the behaviour of the tests changes depending on the environment they
are run in. You should manually test in applicable environments,
until you are confident your change is not a breaking one.

Example steps to test in Integration:

- Click "Configure" for the [Smokey job][]
- Change the "Branch specifier" to the name of your branch
- Run a new build of the Smokey project and check the results

## Deployment

**You need to manually deploy your PR after merging.**

Steps to deploy a change:

- Run the [Smokey deploy job][] to deploy the [continuous Smokey loop][]
- Repeat this in Staging and Production

> The manual [Smokey job][] will pick up changes on `master` automatically. You only need to do a manual deployment for the [continuous Smokey loop][].

[Smokey job]: https://deploy.integration.publishing.service.gov.uk/job/Smokey/
[continuous Smokey loop]: https://github.com/alphagov/govuk-puppet/blob/master/modules/monitoring/templates/smokey-loop.conf
[Smokey deploy job]: https://deploy.integration.publishing.service.gov.uk/job/Smokey_Deploy/

### CODE REVIEW

**Comment by 1pretz1** [comment]
Oh btw I think you need to rebase from `main` to get rid of those unrelated commits.

**Comment by richardTowers** [comment]
Thanks @1pretz1 - rebased.

**Comment by richardTowers** [comment]
Well, the info-frontend tests passed here: https://deploy.integration.publishing.service.gov.uk/job/Smokey/27791/consoleFull

... but other tests failed. I don't _think_ they're related to performance platform. Just broken for other reasons?

**Review by 1pretz1 — APPROVED** [review]
Approving as don't think the other failing tests are related.

I believe the other tests failed due to running smokey with an outdated branch (master vs main). The calculator tests were removed in [this PR](https://github.com/alphagov/smokey/pull/797/files) ~10 days ago. Bet if you ran smokey again, against this branch you may get some success! 👍

**Comment by richardTowers** [comment]
Superseded by #802

**Pull request closed without merging**
