### PR TITLE
Make smokey fail on javascript errors

### PR DESCRIPTION
**Pull request by tijmenb**
This enables turning on javascript for all tests.

This is what it looks like when there is an error:

screen shot 2017-01-12 at 17 07 18

This is follow-up from an incident that occured a few weeks week, where a rogue jQuery upgrade broke a number of pages on GOV.UK.

Trello: https://trello.com/c/WIunrfiT

### CODE REVIEW

**Comment by tijmenb** [comment]
This currently fails on integration:

```
Installing capybara-webkit 1.1.0 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /var/lib/jenkins/bundles/Smokey/ruby/2.3.0/gems/capybara-webkit-1.1.0
/usr/lib/rbenv/versions/2.3.1/bin/ruby -r ./siteconf20170112-3267-oitym5.rb extconf.rb
Command 'qmake -spec linux-g++ ' not available

Makefile not found

Gem files will remain installed in /var/lib/jenkins/bundles/Smokey/ruby/2.3.0/gems/capybara-webkit-1.1.0 for inspection.
Results logged to /var/lib/jenkins/bundles/Smokey/ruby/2.3.0/extensions/x86_64-linux/2.3.0-static/capybara-webkit-1.1.0/gem_make.out
Using http-cookie 1.0.3
An error occurred while installing capybara-webkit (1.1.0), and Bundler cannot
continue.
Make sure that `gem install capybara-webkit -v '1.1.0'` succeeds before
```

https://deploy.integration.publishing.service.gov.uk/job/Smokey/13198/console

We need to install `libqt4-dev libqtwebkit-dev` on the CI servers first,

**Comment by alexmuller** [comment]
This all looks quite reasonable to me but I'll let you finish up the WIP commit 👍

**Comment by MatMoore** [comment]
Just a heads up that some of the scenarios you removed `given` steps for now start with `then`.

Otherwise, looks good so far :1st_place_medal:

**Comment by tijmenb** [comment]
@MatMoore yeah, some of them read quite awkwardly now. To make it easier to review I've removed all the unrelated changes from this PR - I'll remove all the `I am testing through the full stack` and `I force a varnish cache miss` steps in a separate PR.

I'll try to get this passing on integration first.

**Comment by tijmenb** [comment]
It's green on integration now:

https://deploy.integration.publishing.service.gov.uk/job/Smokey/13457/

I've updated the PR description & commit message.

**Comment by rubenarakelyan** [comment]
Nice 👍

**Comment by fofr** [comment]
So good :100:

**Pull request merged**
