### PR TITLE
Add healthcheck scenario for bouncer

### PR DESCRIPTION
**Pull request by ChrisBAshton**
This depends on https://github.com/alphagov/bouncer/pull/278
and would allow us to enable CD for this repo.

Trello: https://trello.com/c/ILpSOFhq/201-enable-cd-for-quick-win-and-possible-quick-win-apps

## Testing

**You should manually test your PR before merging.**

This app doesn't have CI setup, and it would be misleading to do so:
the behaviour of the tests changes depending on the environment they
are run in. You should manually test in applicable environments,
until you are confident your change is not a breaking one.

Example steps to test in Integration:

- Click "Configure" for the [Smokey job][]
- Change the "Branch specifier" to the name of your branch
- Run a new build of the Smokey project and check the results

## Deployment

**You need to manually deploy your PR after merging.**

Steps to deploy a change:

- Run the [Smokey deploy job][] to deploy the [continuous Smokey loop][]
- Repeat this in Staging and Production

> The manual [Smokey job][] will pick up changes on `master` automatically. You only need to do a manual deployment for the [continuous Smokey loop][].

[Smokey job]: https://deploy.integration.publishing.service.gov.uk/job/Smokey/
[continuous Smokey loop]: https://github.com/alphagov/govuk-puppet/blob/master/modules/monitoring/templates/smokey-loop.conf
[Smokey deploy job]: https://deploy.integration.publishing.service.gov.uk/job/Smokey_Deploy/

### CODE REVIEW

**Comment by ChrisBAshton** [comment]
No luck with the current configuration, tested on Smokey integration:

https://deploy.integration.publishing.service.gov.uk/job/Smokey/24812/console

```
Using the integration profile...
@app-bouncer
Feature: Bouncer

  @local-network
  Scenario: Healthcheck                     # features/bouncer.feature:5
    Given I am testing "bouncer" internally # features/step_definitions/smokey_steps.rb:11
    When I request "/healthcheck"           # features/step_definitions/smokey_steps.rb:60
      Unable to fetch 'https://bouncer.integration.govuk-internal.digital/healthcheck'
        Exception: 'Timed out connecting to server'
        Response headers: 
        Response time in seconds: 10.011227425 (RuntimeError)
      ./features/support/http_requests.rb:125:in `rescue in do_http_request'
      ./features/support/http_requests.rb:59:in `do_http_request'
      ./features/support/http_requests.rb:10:in `get_request'
      ./features/step_definitions/smokey_steps.rb:67:in `/^I (try to )?request "(.*)"$/'
      features/bouncer.feature:7:in `I request "/healthcheck"'
    Then JSON is returned                   # features/step_definitions/smokey_steps.rb:270
    And I should see ""status":"ok""        # features/step_definitions/smokey_steps.rb:207
```

Will look again tomorrow.

**Comment by ChrisBAshton** [comment]
@thomasleese I don't suppose you know what URL I need to hit to reach the Bouncer application on integration?
The tests use `http://www.minipax.gov.uk/healthcheck`. I'm also aware of https://www.direct.gov.uk/__canary__ via https://docs.publishing.service.gov.uk/manual/pingdom-bouncer-canary-check.html.

**Comment by thomasleese** [comment]
@ChrisBAshton Maybe `bouncer.{environment}.publishing.service.gov.uk` will work?

**Comment by ChrisBAshton** [comment]
Same issue I'm afraid:

```
Feature: Bouncer

  @local-network
  Scenario: Healthcheck              # features/bouncer.feature:5
    Given I am testing "bouncer"     # features/step_definitions/smokey_steps.rb:3
    When I request "/healthcheck"    # features/step_definitions/smokey_steps.rb:60
      Unable to fetch 'https://bouncer.integration.publishing.service.gov.uk/healthcheck'
        Exception: 'Timed out connecting to server'
        Response headers: 
        Response time in seconds: 10.008441399 (RuntimeError)
      ./features/support/http_requests.rb:125:in `rescue in do_http_request'
      ./features/support/http_requests.rb:59:in `do_http_request'
      ./features/support/http_requests.rb:10:in `get_request'
      ./features/step_definitions/smokey_steps.rb:67:in `/^I (try to )?request "(.*)"$/'
      features/bouncer.feature:7:in `I request "/healthcheck"'
    Then JSON is returned            # features/step_definitions/smokey_steps.rb:270
    And I should see ""status":"ok"" # features/step_definitions/smokey_steps.rb:207

Failing Scenarios:
cucumber -p integration features/bouncer.feature:5 # Scenario: Healthcheck
```

**Comment by ChrisBAshton** [comment]
Ah, I suspect it's this line: https://github.com/alphagov/bouncer/blob/aacf4a8ab3f9165e80d61873b886aba0774a7294/lib%2Fbouncer%2Fapp.rb#L10

```ruby
if context.host.nil? && context.request.path == "/healthcheck"
  Outcome::Healthcheck
```

I'll try removing the `context.host.nil?` check.

**Comment by ChrisBAshton** [comment]
Hmm, _I_ can access https://bouncer.integration.publishing.service.gov.uk/healthcheck directly, but apparently Smokey can't.
I've tried every combination of `internally` (which requests `https://bouncer.integration.govuk-internal.digital/healthcheck`) and not internally, and with/without `@local-network` tag in case that made a difference. Always getting a timeout.

There is an existing Bouncer test but it always seems to go through Production: https://github.com/alphagov/smokey/blob/a751f95547512c9934b2ca0cfcca77797b90bb6b/features%2Fbenchmarking.feature#L6

**Comment by ChrisBAshton** [comment]
I chatted about this with Ben, and we concluded that this is a firewall issue.

Bouncer is on its own machine, and there isn't a firewall rule setup to it (on port 80). Applying a rule to `govuk_bouncer_internal_elb_access` should expose `/healthcheck` to Smokey and get this test passing. We can ask REGOVUK to apply the rule permanently in Terraform, after manually checking on integration.

**Comment by ChrisBAshton** [comment]
That's done it - adding a HTTPS TCP 443 Inbound Rule on the `govuk_bouncer_internal_elb_access` security group, for the `govuk_deploy_access` source: 🎉 

Screenshot 2020-12-01 at 14 48 07

**Comment by ChrisBAshton** [comment]
This now works, as of https://github.com/alphagov/govuk-aws/pull/1378.

**Review by thomasleese — APPROVED** [review]

**Pull request merged**
